name: coba_uas
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  web: 0.3.0
  flutter: 
    sdk: flutter
  firebase_core: 2.27.0
  firebase_auth: 4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  file_picker: ^8.0.0+1
  firebase_database: ^10.4.9
  audioplayers: ^5.2.1
  workmanager: ^0.5.2
  http: ^1.2.0
  flutter_local_notifications: ^17.1.1
  permission_handler: ^11.3.1
  firebase_messaging: ^14.7.19
  timezone: ^0.9.3
  url_launcher: ^6.2.6
  path_provider: ^2.1.3
  shared_preferences: ^2.0.13

  
dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
