// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGSaWx0bxLzVGDqQyePz0OH2NdWdsHiZE',
    appId: '1:813991370846:web:f0273e63fc44b4538794cf',
    messagingSenderId: '813991370846',
    projectId: 'coba-uas-2e05c',
    authDomain: 'coba-uas-2e05c.firebaseapp.com',
    databaseURL: 'https://coba-uas-2e05c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coba-uas-2e05c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIdzxpyryR7ON6qWwchR9WRJX1yxxAX-4',
    appId: '1:813991370846:android:134468302890b1d98794cf',
    messagingSenderId: '813991370846',
    projectId: 'coba-uas-2e05c',
    databaseURL: 'https://coba-uas-2e05c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coba-uas-2e05c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWkssM3qtu9AGeWzLHXwTPMDxCcNN4fBk',
    appId: '1:813991370846:ios:80059d0ed2ab07418794cf',
    messagingSenderId: '813991370846',
    projectId: 'coba-uas-2e05c',
    databaseURL: 'https://coba-uas-2e05c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coba-uas-2e05c.appspot.com',
    iosBundleId: 'com.cobauas.cobaUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWkssM3qtu9AGeWzLHXwTPMDxCcNN4fBk',
    appId: '1:813991370846:ios:80059d0ed2ab07418794cf',
    messagingSenderId: '813991370846',
    projectId: 'coba-uas-2e05c',
    databaseURL: 'https://coba-uas-2e05c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coba-uas-2e05c.appspot.com',
    iosBundleId: 'com.cobauas.cobaUas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGSaWx0bxLzVGDqQyePz0OH2NdWdsHiZE',
    appId: '1:813991370846:web:f158a70219c3d93c8794cf',
    messagingSenderId: '813991370846',
    projectId: 'coba-uas-2e05c',
    authDomain: 'coba-uas-2e05c.firebaseapp.com',
    databaseURL: 'https://coba-uas-2e05c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coba-uas-2e05c.appspot.com',
  );
}
